<?php
//数据库定义
define('host','localhost');
define('user','root');
define('password','root');
define('database','zhaibuqi');
//上传图片文件夹定义
define('UPLOADPATH','../upload-images/');
define('UPLOAD_PATH_FRONT_TO_BACK','upload-images/');
//上传头像文件夹定义
define('UPLOAD_PORTRAIT','../upload-portrait/');
define('UPLOAD_PORTRAIT_FRONT_TO_BACK','upload-portrait/');
define('PORTRAIT','upload-portrait/');
//用户关系定义
define('ATTENTION_NO',0);
define('ATTENTION_ONLY',1);
define('ATTENTION_EACH_OTHER',2);
define('ATTENTION_BY',3);
//用户未登陆
define('USER_NO_LOGIN',-1);
//数据库错误
define('DATABASE_ERROR',-2);