<?php
define('host','localhost');
define('user','root');
define('password','root');
define('database','zhaibuqi');
define('UPLOADPATH','../upload-images/');
define('upload','upload-images/');
define('UPLOADPORTRAIT','../upload-portrait/');
define('PORTRAIT','upload-portrait/');